package contracts

import (
	"bytes"
	"encoding/json"
	"fmt"
	"path/filepath"
	"strings"
)

type GeneratedFile struct {
	Path     string
	Contents []byte
}

func GeneratedFiles() ([]GeneratedFile, error) {
	envelopeJSON, err := marshalJSON(CLIResponseEnvelopeSchema())
	if err != nil {
		return nil, fmt.Errorf("marshal cli response envelope schema: %w", err)
	}

	toolInventoryJSON, err := marshalJSON(mcpToolInventoryDocument())
	if err != nil {
		return nil, fmt.Errorf("marshal mcp tool inventory: %w", err)
	}

	readme, err := renderSchemasREADME()
	if err != nil {
		return nil, err
	}

	return []GeneratedFile{
		{
			Path:     filepath.ToSlash(filepath.Join("docs", "schemas", "cli-response-envelope.json")),
			Contents: envelopeJSON,
		},
		{
			Path:     filepath.ToSlash(filepath.Join("docs", "schemas", "mcp-tools.json")),
			Contents: toolInventoryJSON,
		},
		{
			Path:     filepath.ToSlash(filepath.Join("docs", "schemas", "README.md")),
			Contents: readme,
		},
	}, nil
}

func mcpToolInventoryDocument() map[string]any {
	tools := make([]map[string]any, 0, len(mcpTools))
	for _, tool := range mcpTools {
		tools = append(tools, map[string]any{
			"name":            tool.Name,
			"description":     tool.Description,
			"envelopeCommand": tool.EnvelopeCommand,
			"inputSchema":     tool.InputSchema(),
		})
	}
	return map[string]any{
		"schemaVersion":            AutomationSchemaVersion,
		"generatedFrom":            "internal/contracts",
		"mcpProtocolMethod":        "tools/list",
		"mcpToolInventoryDocument": true,
		"tools":                    tools,
	}
}

func renderSchemasREADME() ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString("# FramesCLI JSON Schemas\n\n")
	buf.WriteString(generatedNotice("./scripts/generate-schemas.sh"))
	buf.WriteString("\nThis directory contains generated agent-facing contract artifacts.\n\n")
	buf.WriteString("## Source of Truth\n\n")
	buf.WriteString("- `internal/contracts/mcp.go`: MCP tool registry and tool-level metadata\n")
	buf.WriteString("- `internal/contracts/inputs.go`: MCP request types shared by runtime decoding and schema generation\n")
	buf.WriteString("- `internal/contracts/schema_reflect.go`: schema derivation from the real request types\n")
	buf.WriteString("- `internal/contracts/schemas.go`: shared schema definitions for generated docs\n\n")
	buf.WriteString("## Generated Files\n\n")
	buf.WriteString("- `README.md`: this generated human-readable reference\n")
	buf.WriteString("- `cli-response-envelope.json`: common automation envelope used by most `--json` CLI commands and MCP tool payloads\n")
	buf.WriteString("- `mcp-tools.json`: machine-readable MCP tool inventory from the registry, including input schemas and emitted envelope command names\n\n")
	buf.WriteString("## MCP Tool Inventory\n\n")
	for i, tool := range mcpTools {
		if i > 0 {
			buf.WriteString("\n")
		}
		buf.WriteString("### `" + tool.Name + "`\n\n")
		buf.WriteString(tool.Description + "\n\n")
		buf.WriteString("- Envelope `command`: `" + tool.EnvelopeCommand + "`\n")
		fields := schemaFieldsFromArgs(tool.Args)
		if len(fields) == 0 {
			buf.WriteString("- Input fields: none\n")
			continue
		}
		buf.WriteString("- Input fields:\n")
		for _, field := range fields {
			line := fmt.Sprintf("  - `%s` (%s)", field.Name, schemaSummary(field.Schema))
			if field.Required {
				line += " required"
			}
			buf.WriteString(line + "\n")
		}
	}
	buf.WriteString("\n")
	buf.WriteString("## Notes\n\n")
	buf.WriteString("- `docs/AGENT_INTEGRATION.md` is the canonical hand-written overview; files in this directory are generated contract references\n")
	buf.WriteString("- `doctor --json` is a separate doctor report shape and is intentionally not described by `cli-response-envelope.json`\n")
	buf.WriteString("- Re-run `./scripts/generate-schemas.sh` after editing the contract registry\n")
	buf.WriteString("- `go test ./cmd/frames -run TestGeneratedAgentContractArtifactsAreCurrent` fails when these generated files drift\n")
	return buf.Bytes(), nil
}

func generatedNotice(command string) string {
	return "<!-- Code generated by " + command + "; DO NOT EDIT. -->"
}

func marshalJSON(v any) ([]byte, error) {
	raw, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		return nil, err
	}
	raw = append(raw, '\n')
	return raw, nil
}

func schemaSummary(schema map[string]any) string {
	if anyOf, ok := schema["anyOf"]; ok {
		options := schemaOptionSummaries(anyOf)
		if len(options) > 0 {
			return strings.Join(options, " or ")
		}
	}

	typeName, _ := schema["type"].(string)
	switch typeName {
	case "array":
		items, _ := schema["items"].(map[string]any)
		itemSummary := schemaSummary(items)
		if itemSummary == "" {
			itemSummary = "any"
		}
		return "array<" + itemSummary + ">"
	case "string":
		if enumValues := enumStrings(schema["enum"]); len(enumValues) > 0 {
			return "string (" + strings.Join(enumValues, ", ") + ")"
		}
		return "string"
	case "integer":
		return "integer"
	case "number":
		if minimum, ok := schema["minimum"]; ok {
			return fmt.Sprintf("number >= %v", minimum)
		}
		return "number"
	case "boolean":
		return "boolean"
	case "object":
		return "object"
	default:
		return "schema"
	}
}

func schemaOptionSummaries(raw any) []string {
	switch options := raw.(type) {
	case []map[string]any:
		out := make([]string, 0, len(options))
		for _, option := range options {
			out = append(out, schemaSummary(option))
		}
		return out
	case []any:
		out := make([]string, 0, len(options))
		for _, option := range options {
			schema, ok := option.(map[string]any)
			if !ok {
				continue
			}
			out = append(out, schemaSummary(schema))
		}
		return out
	default:
		return nil
	}
}

func enumStrings(raw any) []string {
	switch values := raw.(type) {
	case []string:
		return append([]string(nil), values...)
	case []any:
		out := make([]string, 0, len(values))
		for _, value := range values {
			s, ok := value.(string)
			if !ok {
				continue
			}
			out = append(out, s)
		}
		return out
	default:
		return nil
	}
}
